# Generated by Django 5.0.7 on 2024-07-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='username',
        ),
    ]
