# Generated by Django 5.0.7 on 2024-07-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_rename_department_react_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='User',
        ),
    ]
