# Generated by Django 5.0.7 on 2024-07-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_rename_react_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
